name: interview_with_ai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  google_sign_in: ^6.1.5
  provider: ^6.1.1
  permission_handler: ^11.4.0
  http: ^1.2.1
  record: ^5.2.1
  audioplayers: ^5.2.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
